name: AspNetCoreAPI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest-ppc64le
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.115'

    - name: Build with dotnet
      run: dotnet build src\AspNetCoreAPI-GitHubAction.Api\AspNetCoreAPI-GitHubAction.Api.csproj --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest-ppc64le
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    steps:
    - name: Test
      run: dotnet test src\AspNetCoreAPI-GitHubAction.Test
